/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight.vue')['default']
    NaiveTheme: typeof import('./src/components/naive-ui/NaiveTheme.vue')['default']
    NaiveUiApi: typeof import('./src/components/naive-ui/NaiveUiApi.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    YButton: typeof import('./src/components/naive-ui/YButton.vue')['default']
    YCard: typeof import('./src/components/naive-ui/YCard.vue')['default']
    YCheck: typeof import('./src/components/naive-ui/YCheck.vue')['default']
    YDate: typeof import('./src/components/naive-ui/YDate.vue')['default']
    YInput: typeof import('./src/components/naive-ui/YInput.vue')['default']
    YModal: typeof import('./src/components/naive-ui/YModal.vue')['default']
    YPage: typeof import('./src/components/naive-ui/YPage.vue')['default']
    YRadio: typeof import('./src/components/naive-ui/YRadio.vue')['default']
    YSelect: typeof import('./src/components/naive-ui/YSelect.vue')['default']
    YTable: typeof import('./src/components/naive-ui/YTable.vue')['default']
  }
}
